name: app
description: "Project Kanto - offline species classifier."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.11.0
  image: ^4.5.4

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  flutter_riverpod: ^2.5.1
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/model/
    - assets/data/
